### PR TITLE
Php82ready scramsha224broken

### PR DESCRIPTION
**Pull request by schengawegga**

### CODE REVIEW

**Comment by Neustradamus** [comment]
@schengawegga: Good job!

**Review by CloCkWeRX — APPROVED** [review]

**Comment by Neustradamus** [comment]
@CloCkWeRX: Warning it is not in master, can you look?

**Comment by schengawegga** [comment]
> @CloCkWeRX: Warning it is not in master, can you look?

@Neustradamus @CloCkWeRX yes, this is on purpose. I will merge it into master when I prepare the release of the new version in GitHub and pear.php.net.

**Comment by Neustradamus** [comment]
@CloCkWeRX: Can you look for Auth_SASL too?

**Comment by Neustradamus** [comment]
@schengawegga: Good job!
- https://github.com/pear/Auth_SASL2/issues/6
- https://github.com/pear/Auth_SASL2/releases/tag/v0.3.0

Please add the hashtag in the description :)

**Pull request merged**
